/* honeymoon-data.js — 신혼여행 후보 불변 데이터 + 출처 레지스트리 */
var HONEYMOON_SOURCES={
"B1":{t:"Bali Weather",p:"bali.com",u:"https://bali.com/bali/weather/",type:"official",at:"2026-09-07",ad:false},
"B2":{t:"하나투어 발리 허니문",p:"하나투어",u:"https://hanatour.com/mkt/fet/PL00113637",type:"travel_company",at:"2026-09-07",ad:false,fromPrice:true},
"B5":{t:"발리 신혼여행 단점 5가지",p:"reston.tistory.com",u:"https://reston.tistory.com/7",type:"review",at:"2026-09-07",ad:false},
"B7":{t:"발리 11일 예산 후기",p:"blog.naver.com/sukyung9292",u:"https://blog.naver.com/sukyung9292",type:"review",at:"2026-09-07",ad:false},
"J1":{t:"japan-guide When to travel",p:"japan-guide.com",u:"https://japan-guide.com/e/e2273.html",type:"official",at:"2026-09-07",ad:false},
"J4":{t:"Skyscanner ICN-CTS",p:"Skyscanner",u:"https://skyscanner.co.kr",type:"ota",at:"2026-09-07",ad:false},
"J5":{t:"Japan cost guide",p:"radicalstorage.com",u:"https://radicalstorage.com",type:"review",at:"2026-07-03",ad:false},
"V1":{t:"Vietnam Weather Guide",p:"vietnam.travel",u:"https://vietnam.travel/things-to-do/weather-and-climate-vietnam",type:"official",at:"2026-09-07",ad:false},
"V3":{t:"Hoi An in September",p:"ahoyvietnam.com",u:"https://ahoyvietnam.com/hoi-an-in-september/",type:"review",at:"2026-09-07",ad:false},
"IT1":{t:"Italy in Autumn",p:"italyexplained.com",u:"https://italyexplained.com",type:"review",at:"2026-09-07",ad:false},
"IT4":{t:"Korean Air 로마 운임",p:"대한항공",u:"https://koreanair.com",type:"official",at:"2026-09-07",ad:false},
"SP1":{t:"Portugal October guide",p:"kimkim.com",u:"https://kimkim.com",type:"review",at:"2026-09-07",ad:false},
"SP9":{t:"T'way ICN-BCN direct",p:"Trip.com",u:"https://kr.trip.com",type:"official",at:"2026-09-07",ad:false},
"GR1":{t:"Greece in October",p:"santorinidave.com",u:"https://santorinidave.com",type:"review",at:"2026-09-07",ad:false},
"GR5":{t:"Korean Air ICN-ATH",p:"대한항공",u:"https://koreanair.com",type:"official",at:"2026-09-07",ad:false},
"GR6":{t:"Etihad ICN-ATH",p:"Etihad",u:"https://etihad.com",type:"official",at:"2026-09-07",ad:false},
"M1":{t:"Maldives Climate",p:"Maldives Met Service",u:"https://meteorology.gov.mv/climate",type:"official",at:"2026-09-07",ad:false},
"M2":{t:"Webtour 몰디브 패키지",p:"Webtour",u:"https://webtour.com",type:"travel_company",at:"2026-09-07",ad:false,fromPrice:true},
"H1":{t:"Hawaii Weather",p:"honeyfund.com",u:"https://honeyfund.com",type:"review",at:"2026-09-07",ad:false},
"H2":{t:"Chalet Travel 하와이",p:"chalettravel.kr",u:"https://chalettravel.kr",type:"travel_company",at:"2026-09-07",ad:false,fromPrice:true},
"NZ1":{t:"NZ Official Tourism",p:"newzealand.com",u:"https://newzealand.com/kr",type:"official",at:"2026-09-07",ad:false},
"NZ2":{t:"NZ Club 패키지",p:"nzclub.co.kr",u:"https://nzclub.co.kr",type:"travel_company",at:"2026-09-07",ad:false,fromPrice:true},
"S1":{t:"Switzerland Sep guide",p:"Trafalgar",u:"https://trafalgar.com",type:"review",at:"2026-09-07",ad:false},
"S9":{t:"하나투어 스위스 패키지",p:"하나투어",u:"https://hanatour.com",type:"travel_company",at:"2026-09-07",ad:false,fromPrice:true},
"S10":{t:"스위스 9박 실경비",p:"blog.naver.com/yomdunge",u:"https://blog.naver.com/yomdunge/223165591698",type:"review",at:"2026-09-07",ad:false},
"C1":{t:"Dubrovnik Oct weather",p:"TUI",u:"https://tui.co.uk",type:"official",at:"2026-09-07",ad:false},
"C7":{t:"Dubrovnik-Kotor bus",p:"Omio",u:"https://omio.com",type:"ota",at:"2026-09-07",ad:false},
"C12":{t:"크로아티아 신혼여행 후기",p:"블라인드",u:"https://teamblind.com",type:"review",at:"2026-09-07",ad:false}
};

var HONEYMOON_DEST=[
{id:"bali",name:"발리+우붓",region:"동남아시아",
summary:{v:"열대 자연, 프라이빗 풀빌라, 힌두 문화, 래프팅까지 갖춘 허니문 클래식",s:["B1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"9월 건기 꼬리, 10월 전환기. 27°C 내외. 11월은 우기 시작이라 비추천",cautions:["11월 우기 시작: 해변 쓰레기·높은 파도","10월 후반부터 비 잦아짐"]},s:["B1"],st:"official_confirmed"},
trip:{v:{nights:12,route:["스미냑 2박","우붓 2박","시데멘 2박","울루와뚜/누사두아 4박","출국"],segs:[{f:"공항",t:"스미냑",m:"차",d:"30분"},{f:"스미냑",t:"우붓",m:"차",d:"1.5~2.5시간"},{f:"우붓",t:"시데멘",m:"차",d:"1.5시간"},{f:"시데멘",t:"울루와뚜",m:"차",d:"2시간"},{f:"사누르",t:"누사페니다",m:"쾌속선",d:"45분"}]},s:["B5","B7"],st:"single_source"},
exp:{nature:{v:"떼갈랄랑 라이스테라스, 바뚜르산 일출 트레킹, 누사페니다 절벽(켈링킹비치), 스쿰풀 폭포"},rest:{v:"우붓/누사두아 프라이빗 풀빌라, 발리니즈 커플 스파, 짐바란 해변 석양 디너"},culture:{v:"우붓 몽키포레스트, 띠르따엠뿔 사원, 발리 쿠킹클래스, 울루와뚜 케착 파이어댄스"},adventure:{v:"바뚜르산 지프투어, 아융강 래프팅, 누사페니다 스노클링(만타레이), 팀비스 패러글라이딩"}},
mobility:{v:{longHaul:"인천→덴파사르 직항 약 7시간",transfers:["없음(직항)"],fatigue:["발리 교통체증 심각: 31km에 2.5시간 소요 가능","대중교통 없음, Grab/차량 의존"]}},
cons:[{v:"교통체증이 극심해 짧은 거리도 수 시간 소요",s:["B5"],st:"independent_two_source"},{v:"동남아 치고 물가가 비쌈 — 커피 5,000원+, 식사 2만원+/커플",s:["B5"],st:"single_source"},{v:"11월 우기 시 해변 쓰레기·파도·침수 위험",s:["B1"],st:"official_confirmed"},{v:"택시 바가지·호객행위, 우붓 Grab 제한(현지 택시 카르텔)",s:["B5"],st:"single_source"},{v:"우붓/시골 지역 의료 인프라 부족",s:["B5"],st:"single_source"}],
cost:{basis:"가을, 12박, 2인, 이코노미, 중급 숙소",
pkg:{provider:"하나투어",name:"발리 5박 패키지(항공 불포함)",total:null,note:"1인 117~179만원 '부터' 가격. 12박 상품은 없음",s:["B2"],st:"single_source"},
direct:{airfare:{v:200,note:"2인 왕복 약 200만원(LCC~대한항공)",s:["J4"],st:"single_source"},hotel:{v:300,note:"12박 중급 빌라 약 300만원"},other:{v:150,note:"식비·투어·이동 약 150만원"},total:{v:650,note:"2인 약 650만원 추정"}},
ref:"네이버 블로거 11일 2인 약 500만원(2024)",refS:["B7"],validity:"provisional"}
},

{id:"japan",name:"홋카이도+교토",region:"일본",
summary:{v:"단풍 절정의 두 지역을 잇는 자연+미식 여행. 가을의 정석",s:["J1"],st:"official_confirmed"},
autumn:{v:{months:[10,11],cond:"10월 홋카이도 단풍 절정, 교토는 11월 중후반. 9월은 혼슈 태풍 위험",cautions:["9월 혼슈 태풍 시즌","11월 교토 단풍 시즌 숙소 6~8주 전 마감","근로감사의 날(11/21~23) 극심한 혼잡"]},s:["J1"],st:"official_confirmed"},
trip:{v:{nights:12,route:["삿포로 2박","후라노/비에이 1박","노보리베츠 온천 1박","하코다테 1박","교토 3박","나라 당일치기","오사카 1박"],segs:[{f:"삿포로",t:"후라노",m:"JR",d:"2시간"},{f:"후라노",t:"노보리베츠",m:"JR",d:"1.5시간"},{f:"노보리베츠",t:"하코다테",m:"JR",d:"3.5시간"},{f:"하코다테",t:"오사카",m:"국내선",d:"2시간"},{f:"오사카",t:"교토",m:"하루카익스프레스",d:"75분"}]},s:["J1"],st:"single_source"},
exp:{nature:{v:"다이세쓰잔 단풍, 비에이 청의 호수, 하코다테 야경, 아라시야마 대나무숲"},rest:{v:"노보리베츠 온천 료칸, 교토 마치야 숙소, 가이세키 디너, 니시키시장 아침 산책"},culture:{v:"삿포로 라멘요코초·해산물시장, 후시미이나리 신사, 킨카쿠지, 나라 사슴공원, 오사카 도톤보리, 교토 다도체험"},adventure:{v:"다이세쓰잔 국립공원 트레킹, 후라노 자전거 투어, 하코다테 로프웨이, 후시미이나리 정상 등반"}},
mobility:{v:{longHaul:"인천→삿포로 직항 약 3시간, 인천→오사카 직항 약 2시간",transfers:["홋카이도→간사이 국내선 1회"],fatigue:["두 지역 연결에 국내선 필요","JR 열차는 정시·편안하나 하코다테→삿포로 3.5시간"]}},
cons:[{v:"일본 물가 급등: 교토 단풍 시즌 숙소 1박 30~80만원+",s:["J5"],st:"single_source"},{v:"11월 중후반 교토 사찰 극심한 혼잡(도후쿠지, 에이칸도 등)",s:["J1"],st:"official_confirmed"},{v:"홋카이도 시골 영어 소통 어려움",s:["J1"],st:"single_source"},{v:"9월 혼슈 태풍으로 항공·야외 일정 차질 가능",s:["J1"],st:"official_confirmed"},{v:"JR패스·식당예약·사찰 시간 등 사전 계획 필수 — '즉흥 여행' 어려움",s:["J5"],st:"single_source"}],
cost:{basis:"가을, 12박, 2인, 이코노미, 중급 숙소",
pkg:{provider:null,name:null,total:null,note:"일본 10박 이상 허니문 패키지는 한국 여행사에서 일반적이지 않음",s:[],st:"unknown"},
direct:{airfare:{v:150,note:"멀티시티 삿포로in 오사카out 2인 약 150만원"},hotel:{v:400,note:"12박 중급 약 400만원(교토 단풍 시즌 가산)"},other:{v:250,note:"JR패스 2인 80만+식비+입장료 약 250만원"},total:{v:800,note:"2인 약 800만원 추정"}},
ref:"stardrift.ai '10일 $5,000~8,000/커플'",refS:["J5"],validity:"provisional"}
},

{id:"vietnam",name:"다낭+호이안+푸꾸옥",region:"동남아시아",
summary:{v:"가성비 최강이지만 가을은 중부 베트남 태풍·홍수 시즌이라 남부 조합 필수",s:["V1"],st:"official_confirmed"},
autumn:{v:{months:[9],cond:"중부(다낭/호이안) 9~11월은 태풍·홍수 피크. 9월 초만 가능하고 10~11월은 비추천. 남부(푸꾸옥)는 11월부터 건기",cautions:["10~11월 호이안 구시가 침수 반복","태풍 시 해상·야외 활동 전면 취소","다낭 해변 2~3m 파도"]},s:["V1","V3"],st:"official_confirmed"},
trip:{v:{nights:11,route:["다낭 2박","호이안 2박","푸꾸옥 3박(국내선 이동)","호치민 2박"],segs:[{f:"다낭",t:"호이안",m:"택시",d:"30분"},{f:"다낭",t:"푸꾸옥",m:"국내선(호치민경유)",d:"약 2시간"},{f:"푸꾸옥",t:"호치민",m:"국내선",d:"1시간"}]},s:["V1"],st:"single_source"},
exp:{nature:{v:"마블마운틴, 바나힐 골든브릿지, 호이안 시골 자전거, 푸꾸옥 해변·국립공원"},rest:{v:"다낭/푸꾸옥 비치 리조트, 호이안 랜턴 저녁 산책, 베트남 마사지(매우 저렴)"},culture:{v:"호이안 구시가(유네스코), 랜턴마켓, 까오러우/반미/쌀국수, 호치민 전쟁박물관, 쿠치터널, 쿠킹클래스"},adventure:{v:"바나힐 케이블카, 참섬/푸꾸옥 스노클링·다이빙, 오토바이 시골 투어, 투본강 카약"}},
mobility:{v:{longHaul:"인천→다낭 직항 약 4.5시간. 다양한 LCC",transfers:["없음(직항)"],fatigue:["남부 조합 시 국내선 1~2회 추가","다낭↔호이안 30분으로 짧음"]}},
cons:[{v:"9~11월 중부 베트남은 태풍·홍수 피크 시즌 — 가을 신혼여행 최대 리스크",s:["V1","V3"],st:"official_confirmed"},{v:"호이안 호객행위·바가지·택시 사기 반복 보고",s:["V3"],st:"single_source"},{v:"비 오면 핵심 활동(해변·자전거·구시가 산책) 불가, 실내 대안 부족",s:["V3"],st:"single_source"},{v:"다낭 해안 리조트 공사 소음",s:["V3"],st:"single_source"}],
cost:{basis:"가을, 11박, 2인, 이코노미, 중급 숙소",
pkg:{provider:null,name:null,total:null,note:"베트남 10박+ 허니문 패키지 한국 여행사 일반적이지 않음",s:[],st:"unknown"},
direct:{airfare:{v:140,note:"2인 왕복 약 140만원(LCC)"},hotel:{v:150,note:"11박 중급 약 150만원(우기 할인 30~50%)"},other:{v:70,note:"식비·투어·이동 약 70만원(베트남 물가 저렴)"},total:{v:360,note:"2인 약 360만원 추정"}},
ref:null,refS:[],validity:"provisional"}
},

{id:"italy",name:"이탈리아(로마+피렌체+아말피)",region:"남유럽",
summary:{v:"역사·미식·해안 절경을 한 여정에. 유럽 허니문의 정석",s:["IT1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"10월이 최적: 로마 18°C, 아말피 20~25°C. 인파 줄고 가격 하락. 11월은 비 많음",cautions:["11월 비로 아말피 보트투어·하이킹 취소 가능","10월 중후반 아말피 일부 식당 시즌 종료","9월까지는 성수기 가격·인파"]},s:["IT1"],st:"single_source"},
trip:{v:{nights:12,route:["로마 3박","피렌체 3박","아말피코스트(포지타노) 4박","나폴리 2박"],segs:[{f:"로마",t:"피렌체",m:"프레차로사(고속열차)",d:"1시간30분"},{f:"피렌체",t:"나폴리",m:"고속열차",d:"2시간42분"},{f:"나폴리",t:"포지타노",m:"전용차량",d:"1시간30분"}]},s:["IT1"],st:"single_source"},
exp:{nature:{v:"아말피 해안 절벽, 신들의 길(Sentiero degli Dei) 하이킹, 카프리 블루그로토, 키안티 포도밭"},rest:{v:"포지타노 테라스 호텔에서 지중해 조망, 라벨로 석양 아페리티보, 비치클럽 오후"},culture:{v:"콜로세움·바티칸·트레비분수, 우피치미술관, 트라스테베레 푸드투어, 나폴리 피자, 가을 트뤼플/포르치니"},adventure:{v:"폼페이 유적 탐험, 아말피 해안 베스파 렌탈, 카약, 토스카나 쿠킹클래스"}},
mobility:{v:{longHaul:"인천→로마 직항 약 13시간(대한항공/아시아나/티웨이)",transfers:["없음(직항 가능)"],fatigue:["아말피 해안도로 좁고 구불구불 — 멀미 주의","10월 후반 거친 날씨에 페리 결항 가능"]}},
cons:[{v:"아말피 해안도로: 좁고 구불구불해 멀미·교통 지연 빈번",s:["IT1"],st:"single_source"},{v:"로마 관광지·기차역 소매치기·사기 반복 보고",s:["IT1"],st:"single_source"},{v:"11월 비로 보트투어·하이킹·야외 식사 취소 — 환불 어려움",s:["IT1"],st:"single_source"},{v:"9~10월 초 아직 인파 상당",s:["IT1"],st:"single_source"},{v:"관광세·서비스 차지·팁 등 숨은 비용",s:["IT1"],st:"single_source"}],
cost:{basis:"가을, 12박, 2인, 이코노미, 중급 숙소",
pkg:{provider:"여기트래블 등 세미패키지",name:"이탈리아 10~12일",total:null,note:"1인 약 339만원~ (항공+숙소+일부교통). 정확 견적 필요",s:["IT4"],st:"single_source"},
direct:{airfare:{v:300,note:"2인 왕복 약 300만원(대한항공 직항 기준)"},hotel:{v:450,note:"12박 중급 약 450만원(아말피 성수기 가산)"},other:{v:300,note:"식비·열차·입장료·투어 약 300만원"},total:{v:1050,note:"2인 약 1,050만원 추정"}},
ref:"Korean Air 편도 1인 149~176만원(2026 가을)",refS:["IT4"],validity:"provisional"}
},

{id:"spain-portugal",name:"스페인+포르투갈",region:"남유럽",
summary:{v:"바르셀로나 건축+리스본 감성+포르투 와인. 유럽에서 가성비 최고의 도시 투어",s:["SP1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"10월 최적: 바르셀로나 15~23°C, 리스본 22°C. 비 적고 인파 줄어듬. 11월은 비 증가",cautions:["포르투 10월 후반~11월 비 잦음","날씨 변동폭 큼: 반팔→재킷 하루 안에"]},s:["SP1"],st:"single_source"},
trip:{v:{nights:11,route:["바르셀로나 3박","리스본 2박(+신트라 당일)","포르투 2박(+도우루밸리 당일)"],segs:[{f:"바르셀로나",t:"리스본",m:"항공",d:"2시간30분"},{f:"리스본",t:"신트라",m:"기차",d:"40분"},{f:"리스본",t:"포르투",m:"고속열차(AP)",d:"2시간45분"},{f:"포르투",t:"도우루밸리",m:"기차/투어",d:"2시간"}]},s:["SP1"],st:"single_source"},
exp:{nature:{v:"도우루밸리 가을 포도밭 파노라마 열차, 신트라 동화 같은 궁전과 숲, 까보다호까(유럽 최서단)"},rest:{v:"리스본 루프탑바 석양, 바르셀로네타 해변(10월 초 아직 따뜻), 포르투 리베이라 강변 포트와인"},culture:{v:"사그라다파밀리아·가우디 건축, 리스본 알파마/벨렘/파스텔드나타, 포르투 와인셀러(빌라노바드가이아), 보케리아시장 핀초스"},adventure:{v:"고딕쿼터 워킹투어, 에리세이라 서핑(리스본 근교), 포르투 케이블카, 산티아고순례길 시작점"}},
mobility:{v:{longHaul:"인천→바르셀로나 직항 약 15시간(티웨이) 또는 1경유 25시간+",transfers:["직항 가능(티웨이)"],fatigue:["3개 도시라 짐 싸기 잦음","모든 도시 내부는 대중교통 우수"]}},
cons:[{v:"바르셀로나(라스람블라스·지하철)와 리스본(28번 트램·알파마) 소매치기 만연",s:["SP1"],st:"single_source"},{v:"3개 도시 이동으로 공항/역 왕복 시간 소모",s:["SP1"],st:"single_source"},{v:"리스본 언덕 지형이 걷기에 피로",s:["SP1"],st:"single_source"},{v:"포르투 10~11월 비 잦아 야외 활동 제한",s:["SP1"],st:"single_source"},{v:"'리조트 휴식' 구성 요소 없음 — 내내 도시 투어",s:["SP1"],st:"single_source"}],
cost:{basis:"가을, 11박, 2인, 이코노미, 중급 숙소",
pkg:{provider:"여기트래블",name:"스페인+포르투갈 12박 세미패키지",total:null,note:"1인 약 339만원~(항공+숙소+일부교통)",s:["SP9"],st:"single_source"},
direct:{airfare:{v:220,note:"2인 왕복 약 220만원(티웨이 직항 기준)"},hotel:{v:230,note:"11박 중급 약 230만원"},other:{v:180,note:"식비·내부항공·열차·투어 약 180만원"},total:{v:630,note:"2인 약 630만원 추정 — 유럽 중 가성비 최고"}},
ref:"네이버 블로거 11박 1인 약 513만원(배낭)",refS:["SP1"],validity:"provisional"}
},

{id:"greece",name:"그리스(아테네+산토리니+크레타)",region:"남유럽",
summary:{v:"칼데라 절벽 위 허니문의 꿈. 자연+휴식이 압도적이지만 10월 후반부터 비수기 진입",s:["GR1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"10월 초 최적: 산토리니 19~24°C, 해수 23°C. 10월 후반부터 바람 강해지고 업체 시즌오프",cautions:["10월 후반~11월 산토리니 많은 업체·식당 동절기 휴업","바람/날씨로 페리 결항 가능","직항 없음 — 항상 경유 1회 이상"]},s:["GR1"],st:"single_source"},
trip:{v:{nights:12,route:["아테네 3박","산토리니(오이아) 4박","크레타(하니아/레팀노) 5박"],segs:[{f:"아테네",t:"산토리니",m:"국내선/고속페리",d:"50분 항공 / 5시간 페리"},{f:"산토리니",t:"크레타(이라클리온)",m:"고속페리",d:"2시간"},{f:"이라클리온",t:"아테네",m:"국내선",d:"1시간"}]},s:["GR1"],st:"single_source"},
exp:{nature:{v:"산토리니 칼데라·화산 온천, 사마리아 협곡(유럽 최장 협곡), 발로스 라군·엘라포니시 핑크 모래 해변, 오이아 석양"},rest:{v:"산토리니 프라이빗 플런지풀 칼데라 호텔, 화산섬 와인 테이스팅, 크레타 남부 해변에서 휴식"},culture:{v:"아크로폴리스·고대 아고라·플라카, 크레타 크노소스 궁전, 그리스 타베르나(무사카·수블라키·해산물), 산토리니 아시르티코 와인, 올리브오일 테이스팅"},adventure:{v:"산토리니 ATV 라이딩, 칼데라 세일링/카타마란 투어, 크레타 남부 스노클링, 크레타 암벽등반"}},
mobility:{v:{longHaul:"인천→아테네 직항 없음. 이스탄불/두바이 경유 15~19시간",transfers:["항상 경유 1회 이상"],fatigue:["직항 없어 이동일 소모","10월 바람에 페리 결항 위험","크레타는 렌터카 필수(대중교통 부족)"]}},
cons:[{v:"10월 바람/날씨로 섬 간 페리 결항 빈번 — 일정 꼬임 위험",s:["GR1"],st:"single_source"},{v:"산토리니 10월 후반 많은 업체·식당·보트투어 동절기 휴업 — '유령 마을' 느낌",s:["GR1"],st:"single_source"},{v:"직항 없음: 항상 경유, 편도 15~19시간",s:["GR5"],st:"official_confirmed"},{v:"산토리니 칼데라뷰 숙소 극도로 비쌈(1박 20~120만원+)",s:["GR1"],st:"single_source"},{v:"크레타 산악도로 렌터카 스트레스",s:["GR1"],st:"single_source"},{v:"오이아 석양 포인트 10월에도 인파",s:["GR1"],st:"single_source"}],
cost:{basis:"가을, 12박, 2인, 이코노미, 산토리니 중급 칼데라뷰",
pkg:{provider:"젊은여행사블루",name:"그리스 맞춤 허니문",total:null,note:"견적 필요",s:["GR5"],st:"unknown"},
direct:{airfare:{v:280,note:"2인 왕복 약 280만원(에티하드 경유 기준)"},hotel:{v:500,note:"12박 약 500만원(산토리니 중급 칼데라뷰 포함)"},other:{v:300,note:"내부항공+페리+렌터카+식비+투어 약 300만원"},total:{v:1080,note:"2인 약 1,080만원 추정"}},
ref:"네이버 블로거 2인 약 700~1,200만원",refS:["GR1"],validity:"provisional"}
},

{id:"maldives",name:"몰디브",region:"인도양",
summary:{v:"수상빌라·프라이버시의 끝판왕이지만, 10박 이상은 '리조트 감옥' 위험과 극단적 비용",s:["M1"],st:"single_source"},
autumn:{v:{months:[11],cond:"9~10월은 남서몬순 우기 피크(강수 200mm+). 11월부터 건기 전환 — 가격도 아직 숄더. 9~10월은 비추천",cautions:["9~10월 시야 저하로 스노클링/다이빙 불리","거친 바다로 수상비행기 지연/결항 가능","11월이 가을 유일한 적합 시기"]},s:["M1"],st:"official_confirmed"},
trip:{v:{nights:10,route:["말레 도착→리조트1 수상빌라 4박","말레 시내 1일","리조트2 비치빌라 3박","로컬섬 방문 당일","말레→귀국"],segs:[{f:"말레",t:"리조트",m:"스피드보트/수상비행기",d:"30~90분"},{f:"리조트1",t:"말레",m:"스피드보트",d:"30~60분"},{f:"말레",t:"리조트2",m:"수상비행기",d:"30~45분"}]},s:["M1"],st:"single_source"},
exp:{nature:{v:"산호초 스노클링, 고래상어·만타레이 만남(9~11월 동쪽 베스트), 모래톱 방문, 야광 플랑크톤 해변"},rest:{v:"프라이빗 수상빌라, 커플 스파, 인피니티풀, 해변 프라이빗 디너"},culture:{v:"말레 피시마켓·후쿠루미스키 모스크, 몰디브 전통요리(마스후니·가루디야), 수중 레스토랑 다이닝, 로컬섬 홈스테이 방문"},adventure:{v:"스쿠버다이빙, 제트스키, 파라세일링, 석양 돌고래 크루즈, 나이트피싱"}},
mobility:{v:{longHaul:"인천→말레 직항 약 10시간(대한항공). 싱가포르/두바이 경유도 가능",transfers:["없음(직항 가능)"],fatigue:["리조트 간 이동에 스피드보트/수상비행기 필수(편도 30~90분)","수상비행기는 주간만 운항, 날씨 의존"]}},
cons:[{v:"3~4일 후 '리조트 감옥' 느낌 — 단조로운 활동, 제한된 선택지",s:["M1"],st:"single_source"},{v:"숨은 비용 극단적: 리조트 물 $5~10, 칵테일 $15~25, 식사 $50~150/인. GST 16%+그린택스+서비스10%",s:["M1"],st:"single_source"},{v:"9~10월 날씨 위험: 종일 비, 수상비행기 결항, 시야 저하",s:["M1"],st:"official_confirmed"},{v:"도시/문화 경험 거의 없음 — 말레는 작고 관광 친화적이지 않음",s:["M1"],st:"single_source"},{v:"10박 이상 일정 구성 어려움: 대부분 패키지 4~7박, 멀티리조트는 이동비 폭증",s:["M1"],st:"single_source"}],
cost:{basis:"가을(11월), 10박, 2인, 이코노미, 중급 리조트",
pkg:{provider:"웹투어",name:"몰디브 리조트 패키지",total:null,note:"벨리간두 1인 275만원~ '부터' 가격. 10박 패키지는 일반적이지 않음",s:["M2"],st:"single_source"},
direct:{airfare:{v:240,note:"2인 왕복 약 240만원(대한항공 직항)"},hotel:{v:800,note:"10박 중급 리조트 약 800만원(수상빌라 4박+비치빌라 3박+말레)"},other:{v:400,note:"수상비행기 이동+식사+액티비티+세금 약 400만원"},total:{v:1440,note:"2인 약 1,440만원 추정 — 후보 중 최고가"}},
ref:null,refS:[],validity:"provisional"}
},

{id:"hawaii",name:"하와이(오아후+마우이)",region:"태평양",
summary:{v:"자연+도시+액티비티 균형 최고. 시차 19시간이 유일한 약점",s:["H1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"9~10월 건기 꼬리: 26~31°C, 강수 적고 인파 줄어드는 숄더시즌. 11월부터 우기 전환",cautions:["11월 비 증가·간헐적 폭풍","시차 19시간: 첫 1~2일 시차적응 소모"]},s:["H1"],st:"single_source"},
trip:{v:{nights:12,route:["오아후(와이키키) 5박","마우이(카아나팔리/와일레아) 7박"],segs:[{f:"인천",t:"호놀룰루",m:"직항",d:"8~9시간"},{f:"오아후",t:"마우이",m:"하와이안항공 국내선",d:"40분"}]},s:["H1"],st:"single_source"},
exp:{nature:{v:"다이아몬드헤드, 할레아칼라 화산 일출, 몰로키니 스노클링, 하나로드 폭포·대나무숲, 노스쇼어 해변"},rest:{v:"와일레아/카아나팔리 비치 리조트, 오션프론트 스파, 풀사이드 선셋 칵테일"},culture:{v:"진주만, 폴리네시안문화센터, 라하이나 역사마을, 루아우 디너쇼, 포케/로코모코/셰이브아이스/팜투테이블"},adventure:{v:"와이키키 서핑 레슨, 할레아칼라 일출, 하나로드 드라이브, 쿠알로아 집라인, 헬리콥터 투어"}},
mobility:{v:{longHaul:"인천→호놀룰루 직항 약 8~9시간(대한항공/아시아나/에어프레미아)",transfers:["없음(직항)"],fatigue:["시차 19시간이 최대 피로 요인","양 섬 모두 렌터카 필수","섬 간 이동에 공항 시간+추가 항공"]}},
cons:[{v:"미국 최고가 목적지 중 하나: 리조트피 $30~50/박, 주차 $30~50/박, 식사 $30~60/인, 팁 18~25%",s:["H1"],st:"single_source"},{v:"인기 스팟 혼잡: 와이키키 극심, 하나로드 교통/주차, 스노클링 포인트 붐빔",s:["H1"],st:"single_source"},{v:"직항 8~9시간+시차 19시간: 아시아 여행자 첫 1~2일 시차적응에 소모",s:["H1"],st:"single_source"},{v:"섬 간 이동 비용·시간: 왕복 항공 2인 40~80만원+공항 시간+렌터카 재대여",s:["H1"],st:"single_source"},{v:"11월 날씨 불확실: 우기 시작, 간헐적 폭풍",s:["H1"],st:"single_source"}],
cost:{basis:"가을, 12박, 2인, 이코노미, 중급 리조트",
pkg:{provider:"샬레트래블",name:"오아후+마우이 6박8일",total:null,note:"1인 387만원~ '부터' 가격. 12박 패키지는 별도",s:["H2"],st:"single_source"},
direct:{airfare:{v:240,note:"2인 왕복 약 240만원(에어프레미아 직항 기준)"},hotel:{v:600,note:"12박 중급 리조트 약 600만원(리조트피·주차 포함)"},other:{v:400,note:"렌터카 12일+섬간 항공+식비+액티비티 약 400만원"},total:{v:1240,note:"2인 약 1,240만원 추정"}},
ref:"Trip.com '허니문 5박7일 800~1,200만원/2인' 비례 추정",refS:["H1"],validity:"provisional"}
},

{id:"nz",name:"뉴질랜드(남북섬)",region:"오세아니아",
summary:{v:"피요르드·빙하·번지·와인까지 모험과 자연의 교과서. 가을=뉴질랜드 봄이라 꽃·초록이 폭발",s:["NZ1"],st:"official_confirmed"},
autumn:{v:{months:[10,11],cond:"한국 가을 = 뉴질랜드 봄. 10~11월 기온 상승·일조 길어짐. 남섬 9~10월은 아직 춥고 눈 가능",cautions:["9월 남섬 산악 지역 눈·폐쇄 가능","날씨 '하루에 사계절' 변동","자외선 매우 강함(9~4월)"]},s:["NZ1"],st:"official_confirmed"},
trip:{v:{nights:13,route:["오클랜드 1박","호비튼+와이토모 당일","로토루아 2박","오클랜드→크라이스트처치 국내선","레이크테카포 1박","마운트쿡 1박","퀸스타운 3박(+밀포드사운드 당일)","와나카 1박","프란츠조셉 빙하 1박","크라이스트처치 1박"],segs:[{f:"오클랜드",t:"로토루아",m:"차",d:"3시간"},{f:"오클랜드",t:"크라이스트처치",m:"국내선",d:"1시간15분"},{f:"크라이스트처치",t:"테카포",m:"차",d:"3.5시간"},{f:"테카포",t:"퀸스타운",m:"차(린디스패스)",d:"3.5시간"},{f:"퀸스타운",t:"밀포드사운드",m:"투어버스",d:"편도4시간"},{f:"퀸스타운",t:"와나카",m:"차",d:"1시간"},{f:"와나카",t:"프란츠조셉",m:"차",d:"4.5시간"},{f:"프란츠조셉",t:"크라이스트처치",m:"차(아서스패스)",d:"4시간"}]},s:["NZ1"],st:"single_source"},
exp:{nature:{v:"밀포드사운드 피요르드, 마운트쿡 후커밸리, 테카포 호수 별 관측, 통가리로 알파인 크로싱, 프란츠조셉 빙하, 로토루아 지열지대, 와나카 호수"},rest:{v:"로토루아 온천 스파, 호수변 롯지 숙소, 센트럴오타고 와인지역, 퀸스타운 럭셔리 숙소"},culture:{v:"마오리 문화체험(항이·하카), 호비튼 무비세트, 뉴질랜드 양고기·해산물·와인, 퀸스타운 퍽버거, 크래프트 맥주"},adventure:{v:"퀸스타운 번지점프(발상지), 제트보트, 빙하 헬리하이크, 스카이다이빙, 밀포드 카약, 후커밸리 트레킹"}},
mobility:{v:{longHaul:"인천→오클랜드 직항 약 11~12시간(대한항공/에어뉴질랜드)",transfers:["없음(직항 가능)"],fatigue:["남섬 총 주행 1,500~2,000km: 구간당 3~4.5시간","좌측통행 스트레스","대중교통 거의 없어 렌터카 필수"]}},
cons:[{v:"남섬 장거리 운전 필수: 구간당 3~5시간, 총 1,500km+. 좌측통행이 한국인에겐 스트레스",s:["NZ1"],st:"single_source"},{v:"9~10월 여전히 춥고(퀸스타운 5~15°C) 날씨 급변 잦음. 일부 고산 트레킹 폐쇄",s:["NZ1"],st:"official_confirmed"},{v:"식비·액티비티 비쌈: 식사 $20~40 NZD, 번지 $200+, 헬리하이크 $400+, 밀포드 크루즈 $200+",s:["NZ1"],st:"single_source"},{v:"퀸스타운/오클랜드 외 식당 선택지 제한적. 작은 마을 일찍 닫힘. 나이트라이프 거의 없음",s:["NZ1"],st:"single_source"},{v:"직항 11~12시간+시차 3~4시간",s:["NZ1"],st:"single_source"}],
cost:{basis:"가을(10~11월=NZ 봄), 13박, 2인, 이코노미, 중급",
pkg:{provider:"NZ Club",name:"남북섬 럭셔리 11일",total:null,note:"1인 845만원~ '부터' 가격",s:["NZ2"],st:"single_source"},
direct:{airfare:{v:300,note:"2인 왕복 약 300만원(대한항공/에어NZ)"},hotel:{v:350,note:"13박 중급 약 350만원"},other:{v:350,note:"렌터카13일+국내선+식비+액티비티 약 350만원"},total:{v:1000,note:"2인 약 1,000만원 추정"}},
ref:"네이버 블로거 14일 셀프드라이브 2인 약 700~1,000만원",refS:["NZ2"],validity:"provisional"}
},

{id:"swiss-austria",name:"스위스+오스트리아",region:"중부유럽",
summary:{v:"알프스 절경+비엔나 문화. 가을 산악 단풍과 파노라마 열차가 압권이지만 유럽 최고가",s:["S1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"9월 최적: 취리히 10~19°C, 맑고 건조. 10월 단풍, 할인 숙소. 11월은 우중충하고 일부 산악 시설 폐쇄",cautions:["산악 날씨 급변 — 케이블카·전망대 구름/안개로 조망 불가 가능","10월 중후반 고산 케이블카·트레킹 코스 폐쇄 시작","11월 비추천"]},s:["S1"],st:"single_source"},
trip:{v:{nights:11,route:["취리히 2박","루체른 2박","인터라켄 2박","할슈타트 1박","잘츠부르크 2박","비엔나 2박"],segs:[{f:"취리히",t:"루체른",m:"기차",d:"45분"},{f:"루체른",t:"인터라켄",m:"골든패스(파노라마)",d:"2시간"},{f:"인터라켄",t:"할슈타트",m:"기차(잘츠부르크 경유)",d:"4.5시간"},{f:"할슈타트",t:"잘츠부르크",m:"기차",d:"1.5시간"},{f:"잘츠부르크",t:"비엔나",m:"레일젯",d:"2.5시간"}]},s:["S1"],st:"single_source"},
exp:{nature:{v:"루체른호수, 융프라우요흐/쉴트호른, 할슈타트 호수, 인터라켄 알프스 파노라마, 골든패스 파노라마 열차"},rest:{v:"루체른 호수변 숙소, 인터라켄 스파호텔, 비엔나 카페하우스 문화, 파노라마 열차 안에서의 여유"},culture:{v:"취리히 구시가, 잘츠부르크(모차르트/사운드오브뮤직), 비엔나(쇤브룬·벨베데레·오페라), 스위스 퐁뒤/라클렛, 비엔나 자허토르테/슈니첼"},adventure:{v:"인터라켄 패러글라이딩, 그린델발트 퍼스트 하이킹, 융프라우요흐 산악열차, 잘츠부르크 소금광산"}},
mobility:{v:{longHaul:"인천→취리히 직항 약 12시간(스위스항공)",transfers:["없음(직항 가능)"],fatigue:["인터라켄→할슈타트 4.5시간 최장 구간","5개 도시 11박으로 잦은 짐 싸기","유럽 기차 정시·편안"]}},
cons:[{v:"스위스 물가 극단적: 식사 1인 16CHF+, 커플 하루 식비만 100CHF+ 쉽게 초과",s:["S10"],st:"single_source"},{v:"산악 날씨 급변: 10~11월 케이블카·전망대 구름으로 조망 불가 빈번",s:["S1"],st:"single_source"},{v:"할슈타트 오버투어리즘: 인구 700명 마을에 당일 관광객 폭주. 제한적 숙소·식당",s:["S1"],st:"single_source"},{v:"5개 도시 11박 = 잦은 이동·짐 싸기. 인터라켄→할슈타트 4.5시간",s:["S1"],st:"single_source"}],
cost:{basis:"가을, 11박, 2인, 이코노미, 중급 숙소",
pkg:{provider:"하나투어",name:"스위스 일주 9일(4성)",total:null,note:"1인 499만원~ '부터' 가격. 오스트리아 포함 11박은 별도 구성",s:["S9"],st:"single_source"},
direct:{airfare:{v:250,note:"2인 왕복 오픈조(취리히in 비엔나out) 약 250만원"},hotel:{v:500,note:"11박 중급 약 500만원(스위스 고가 반영)"},other:{v:350,note:"스위스트래블패스+오스트리아 열차+식비+입장 약 350만원"},total:{v:1100,note:"2인 약 1,100만원 추정"}},
ref:"네이버 블로거 스위스 9박 2인 총 약 1,200만원(숙 560만 포함)",refS:["S10"],validity:"provisional"}
},

{id:"croatia",name:"크로아티아+몬테네그로",region:"남유럽·발칸",
summary:{v:"아드리아해 절벽도시+유네스코 올드타운+섬. 유럽 허니문의 숨은 보석이지만 직항 없음",s:["C1"],st:"single_source"},
autumn:{v:{months:[9,10],cond:"9월 늦여름: 두브로브니크 18~26°C, 해수 23°C. 10월 온화: 14~21°C. 11월은 비·추위로 비추천",cautions:["10월 비 강도 높을 수 있음(집중호우)","11월 섬 페리 축소·소규모 타운 영업 종료","크루즈선 기항 시 두브로브니크 극심한 혼잡"]},s:["C1"],st:"official_confirmed"},
trip:{v:{nights:11,route:["두브로브니크 3박","코토르(몬테네그로) 2박","부드바/스베티스테판 당일","스플리트 2박","흐바르섬 2박"],segs:[{f:"두브로브니크",t:"코토르",m:"버스",d:"2시간"},{f:"코토르",t:"스플리트",m:"버스(해안도로)",d:"6시간40분"},{f:"스플리트",t:"흐바르",m:"카타마란 페리",d:"1시간"}]},s:["C1","C7"],st:"single_source"},
exp:{nature:{v:"코토르만(유럽 최남단 피요르드), 로크룸섬(두브로브니크), 흐바르 라벤더밭, 블루케이브"},rest:{v:"흐바르 해변(스티니바·두보비차), 스베티스테판 전망, 두브로브니크 성벽 위 석양, 스플리트 워터프론트 카페"},culture:{v:"두브로브니크 올드타운(유네스코), 디오클레티아누스 궁전(스플리트, 유네스코), 코토르 올드타운(유네스코), 신선 해산물, 크로아티아/몬테네그로 와인, 왕좌의게임 촬영지"},adventure:{v:"두브로브니크 성벽 바다카약, 흐바르 블루케이브 보트투어, 코토르 요새 등반(1,350계단), 체티나강 집라인(스플리트 근교)"}},
mobility:{v:{longHaul:"인천→두브로브니크 직항 없음. 이스탄불/프랑크푸르트 경유 16~20시간",transfers:["항상 경유 1~2회"],fatigue:["직항 없음: 편도 16~20시간","코토르→스플리트 버스 6시간40분 해안 구불길","두브로브니크→스플리트 보스니아(네움) 통과 = 이중 국경검문"]}},
cons:[{v:"두브로브니크 오버투어리즘: 크루즈선 기항 시 구시가 극심한 혼잡, 입장 제한",s:["C1"],st:"single_source"},{v:"코토르→스플리트 버스 6.5시간+, 해안 구불길. 보스니아 국경 이중 통과",s:["C7","C12"],st:"single_source"},{v:"두브로브니크 숙소·식당 비쌈: 시즌 좋은 호텔 1박 $250+",s:["C12"],st:"single_source"},{v:"소규모 타운 식당 선택지 제한적. 코토르 올드타운 빨리 질림",s:["C12"],st:"single_source"},{v:"직항 없음: 항상 경유 1~2회, 편도 16~20시간",s:["C1"],st:"official_confirmed"}],
cost:{basis:"가을, 11박, 2인, 이코노미, 중급 숙소",
pkg:{provider:null,name:null,total:null,note:"크로아티아+몬테네그로 전용 허니문 패키지 한국 여행사에서 일반적이지 않음",s:[],st:"unknown"},
direct:{airfare:{v:250,note:"2인 왕복 약 250만원(경유 1회 기준)"},hotel:{v:300,note:"11박 중급 약 300만원"},other:{v:180,note:"내부 버스+페리+식비+투어 약 180만원"},total:{v:730,note:"2인 약 730만원 추정"}},
ref:"블라인드 유저 '싸게 하려고 반자유여행 했는데 렌트비 별도라 비쌌다'",refS:["C12"],validity:"provisional"}
}
];
